# This is a basic workflow to help you get started with Actions

name: Pull Request Quality Checks

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: PR checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          token: ${{ secrets.TS_GH_BOT }}
      - run: |
          npm ci;
          npm run qa;
          node .github/workflows/dependency-check.js;
          changeType=$(<.version-change-type)
          if [ -z "$changeType" ];
            then
              echo "missing file .version-change-type!"
              exit 1
          fi
          echo "Checking for release notes..."
          git fetch origin main ${{ github.event.pull_request.base.sha }};
          diff=$(git diff -U0 ${{ github.event.pull_request.base.sha }} ${{ github.sha }} RELEASENOTES.md);
          if [ -z "$diff" ]; then echo "Missing release notes! exiting..."; exit 1; fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TS_GH_BOT }}
          NODE_OPTIONS: "--max-old-space-size=8192"
