# This is a basic workflow to help you get started with Actions

name: Pull Request Quality Checks

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: PR checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
        token: ${{ secrets.TS_GH_BOT }}
    - run: |
        npm ci;
        npm run qa;
        npm run build;
        node .github/workflows/dependency-check.js
      env:
        NODE_AUTH_TOKEN: ${{ secrets.TS_GH_BOT }}
